# Generated by Django 3.2.4 on 2021-06-25 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 17, 52, 50, 399152)),
        ),
    ]
