# Generated by Django 3.2.4 on 2021-06-25 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 18, 34, 10, 399782)),
        ),
    ]
